'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'en' | 'ar'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Brand
    'brand.name': 'Faheem',
    'brand.tagline': 'Smart customer support built for the Arab market',

    // Navigation
    'nav.home': 'Home',
    'nav.pricing': 'Pricing',
    'nav.login': 'Login',
    'nav.register': 'Sign Up',
    'nav.search': 'Search...',
    'nav.dashboard': 'Dashboard',
    'nav.create': 'Create Knowledge',
    'nav.notifications': 'Notifications',
    'nav.no_notifications': 'No new notifications',
    'nav.email': 'Email',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',

    // Footer
    'footer.quick_links': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact Us',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.rights': 'All rights reserved',
    'footer.twitter': 'Twitter',
    'footer.facebook': 'Facebook',
    'footer.linkedin': 'LinkedIn',

    // Login Page
    'login.welcome_back': 'Welcome Back',
    'login.subtitle': 'Sign in to access your dashboard',
    'login.email': 'Email Address',
    'login.email_placeholder': 'example@example.com',
    'login.password': 'Password',
    'login.password_placeholder': '********',
    'login.submit': 'Sign In',
    'login.loading': 'Signing in...',
    'login.no_account': "Don't have an account?",
    'login.create_account': 'Create an account now',
    'login.new_here': 'New here?',
    'login.error': 'Invalid email or password',

    // Onboarding Page
    'onboarding.welcome': 'Welcome',
    'onboarding.subtitle': "Let's set up your account for maximum success",
    'onboarding.step.company': 'Company',
    'onboarding.step.usecase': 'Use Case',
    'onboarding.step.languages': 'Languages',
    'onboarding.company.title': 'What is your company or project name?',
    'onboarding.company.subtitle': 'We will use this name in your account details',
    'onboarding.company.placeholder': 'e.g., Al-Najm Company',
    'onboarding.usecase.title': 'How will you use Faheem?',
    'onboarding.usecase.subtitle': 'Choose the primary use case',
    'onboarding.usecase.support': 'Customer Support',
    'onboarding.usecase.sales': 'Sales',
    'onboarding.usecase.education': 'Education',
    'onboarding.usecase.healthcare': 'Healthcare',
    'onboarding.usecase.ecommerce': 'E-commerce',
    'onboarding.usecase.other': 'Other',
    'onboarding.languages.title': 'What are the bot languages?',
    'onboarding.languages.subtitle': 'Choose the languages your bot will speak',
    'onboarding.prev': 'Previous',
    'onboarding.next': 'Next',
    'onboarding.finish': 'Finish',
    'onboarding.finishing': 'Finishing...',

    // Register Page
    'register.title': 'Get Started with Faheem',
    'register.subtitle': 'Create your free account now',
    'register.first_name': 'First Name',
    'register.last_name': 'Last Name',
    'register.email': 'Email Address',
    'register.phone': 'Phone Number',
    'register.password': 'Password',
    'register.confirm_password': 'Confirm Password',
    'register.password_hint': 'Password must be at least 8 characters',
    'register.submit': 'Create Account',
    'register.loading': 'Creating account...',
    'register.has_account': 'Already have an account?',
    'register.sign_in': 'Sign In',
    'register.error.first_name': 'First name is required',
    'register.error.last_name': 'Last name is required',
    'register.error.email': 'Email is required',
    'register.error.phone': 'Phone number is required',
    'register.error.password_length': 'Password must be at least 8 characters',
    'register.error.password_match': 'Passwords do not match',
    'register.error.general': 'An error occurred while creating the account',
    'dashboard.title': 'Control Panel',
    'dashboard.subtitle': 'Bot Performance Summary',
    'dashboard.daily_chats': 'Daily Conversations',
    'dashboard.customer_satisfaction': 'Customer Satisfaction',
    'dashboard.active_users': 'Active Users',
    'dashboard.growth': 'Growth',
    'dashboard.coming_soon': 'Coming Soon',
    'dashboard.advanced_analytics': 'Advanced analytics and detailed reports coming soon',
    'knowledge.title': 'Knowledge & Instructions',
    'knowledge.subtitle': 'Add knowledge and instructions for your bot',
    'knowledge.add_new': 'Add New Knowledge',
    'knowledge.manual_text': 'Manual Text',
    'knowledge.upload_file': 'Upload File',
    'knowledge.title_label': 'Title',
    'knowledge.title_placeholder': 'e.g., Return Policy',
    'knowledge.description_label': 'Description',
    'knowledge.description_placeholder': 'Enter the knowledge you want to add...',
    'knowledge.add': 'Add',
    'knowledge.cancel': 'Cancel',
    'knowledge.drag_files': 'Drag files here or click to upload',
    'knowledge.file_types': 'PDF, DOCX, TXT, CSV (max 10 MB per file)',
    'knowledge.upload': 'Upload File',
    'knowledge.no_knowledge': 'No knowledge added',
    'knowledge.no_knowledge_desc': 'Start by adding knowledge and instructions for your bot',
    'knowledge.add_now': 'Add Now',
    'knowledge.type.manual': 'Manual',
    'knowledge.type.product': 'Product',
    'knowledge.type.file': 'File',
    'knowledge.content_label': 'Content',
    'knowledge.content_placeholder': 'Write the content here...',
    'knowledge.product_name': 'Product Name',
    'knowledge.price': 'Price',
    'knowledge.category': 'Category',
    'knowledge.description': 'Description',
    'knowledge.drag_drop': 'Drag file here or click to select',
    'knowledge.supported_formats': 'Supported formats: PDF, DOC, DOCX',
    'knowledge.error.unsupported': 'Unsupported file format. (PDF, DOC, DOCX only)',
    'knowledge.error.too_large': 'File too large (Max 10MB)',
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.personal_info': 'Personal Information',
    'profile.personal_info_desc': 'Manage your basic personal details',
    'profile.first_name': 'First Name',
    'profile.last_name': 'Last Name',
    'profile.phone': 'Phone Number',
    'profile.not_provided': 'Not Provided',
    'profile.security': 'Security & Account',
    'profile.security_desc': 'Security and privacy settings',
    'profile.status': 'Account Status',
    'profile.active': 'Active',
    'profile.verified': 'Verified',
    'profile.join_date': 'Join Date',
    'profile.bot_settings': 'Bot Settings',
    'profile.bot_settings_desc': 'Want to change your bot configurations?',
    'profile.go_to_settings': 'Go to Settings',
    'profile.save_changes': 'Save Changes',
    'sidebar.messages': 'Messages',
    'sidebar.knowledge': 'Knowledge Base',
    'sidebar.channels': 'Channels',
    'sidebar.inbox': 'Inbox',
    'sidebar.settings': 'Settings',
    'sidebar.active_bot': 'Active Bot',
    'sidebar.new_bot': 'New Bot',
    'sidebar.language': 'Language',
    'sidebar.no_bot': 'No Bot Selected',
    'sidebar.menu': 'Menu',
    'sidebar.profile': 'Profile',
    'sidebar.logout': 'Logout',
    'auth.welcome_back': 'Welcome back!',
    'auth.account_created': 'Account created successfully!',
    'auth.logged_out': 'Logged out successfully',
    'auth.login_failed': 'Login failed',
    'auth.register_failed': 'Registration failed',
    'auth.onboarding_complete': 'Onboarding completed successfully!',
    'auth.onboarding_failed': 'Failed to save onboarding data',
    'auth.onboarding_saving': 'Saving onboarding data...',
    'auth.already_logged_in': 'You are already logged in!',
    'error.invalid_credentials': 'Invalid credentials',
    'error.user_not_found': "User doesn't exist",
    'error.incorrect_password': 'Incorrect password',
    'error.unsupported_file': 'Unsupported file type. Use: PDF, DOCX, TXT, CSV',
    'error.file_too_large': 'File size must be less than 10 MB',
    'hero.title_start': 'Setup your smart agent in',
    'hero.title_end': 'minutes',
    'hero.description': 'Customer support that feels human, even if it\'s AI. Faheem detects emotions, handles routine inquiries, and seamlessly escalates complex cases to your team.',
    'hero.cta': 'Start Free Trial',
    'hero.assistant_icon': 'F',
    'hero.assistant_name': 'Faheem',
    'hero.online': 'Online now',
    'hero.greeting': 'Hi! How can I help you today? 👋',
    'hero.user_message': 'I want to know working hours',
    'hero.bot_response': 'Sure! We\'re open from 9 AM to 6 PM, Saturday to Thursday 🕐',
    'hero.input_placeholder': 'Type your message...',
    'features.title': 'Why Choose Faheem?',
    'features.analytics': 'Comprehensive Analytics',
    'features.analytics_desc': 'Track your bots\' performance and understand customer behavior',
    'features.security': 'High Security',
    'features.security_desc': 'Protect your customer data with the highest security standards',
    'features.customization': 'Easy Customization',
    'features.customization_desc': 'Customize the bot according to your business needs',
    'features.support': 'Excellent Support',
    'features.support_desc': 'Support team available 24/7 to help you',
    'features.leads': 'Lead Generation',
    'features.leads_desc': 'Faheem extracts potential customers from conversations',
    'features.integration': 'Integration',
    'features.integration_desc': 'Faheem responds to every customer on every platform',
    'pricing.title': 'Simple and Transparent Pricing',
    'pricing.subtitle': 'Choose the plan that fits your business needs',
    'pricing.trial': 'Trial Plan',
    'pricing.trial_desc': 'For part-time workers',
    'pricing.trial_cta': 'Get Started',
    'pricing.starter': 'Starter Plan',
    'pricing.starter_desc': 'For full-time workers',
    'pricing.pro': 'Professional Plan',
    'pricing.pro_desc': 'For large enterprises',
    'pricing.free': 'Free',
    'pricing.per_month': '/month',
    'pricing.messages_100': '100 messages/month',
    'pricing.messages_1k': '1,000 messages/month',
    'pricing.messages_5k': '5,000 messages/month',
    'pricing.agents_1': '1 agent',
    'pricing.agents_3': '3 agents',
    'pricing.agents_10': '10 agents',
    'pricing.platform_1': '1 platform',
    'pricing.platform_3': '3 platforms',
    'pricing.platform_unlimited': 'Unlimited platforms',
    'pricing.basic_support': 'Basic support',
    'pricing.priority_support': 'Priority support',
    'pricing.custom_support': 'Custom support 24/7',
    'pricing.advanced_analytics': 'Advanced analytics',
    'pricing.custom_analytics': 'Custom analytics',
    'pricing.custom_integrations': 'Custom integrations',
    'trusted.title': 'Trusted by Industry Leaders',
    'trusted.subtitle': 'Thousands of companies use Faheem to improve their customer support',
    'trusted.companies': 'Companies Using Faheem',
    'trusted.conversations': 'Conversations Handled',
    'trusted.uptime': 'Uptime Guarantee',
    'cta.title': 'Ready to improve your customer service?',
    'cta.description': 'Join thousands of companies that use Faheem to provide exceptional customer support. Start your free trial today with no credit card required.',
    'cta.button_primary': 'Start Free Trial',
    'cta.button_secondary': 'View Pricing',
    'cta.no_credit_card': 'No credit card required. Just login',

    // Inbox
    'inbox.title': 'Inbox',
    'inbox.conversations': 'Conversations',
    'inbox.search': 'Search conversations...',
    'inbox.filter_all': 'All',
    'inbox.filter_active': 'Active',
    'inbox.filter_pending': 'Pending',
    'inbox.filter_resolved': 'Resolved',
    'inbox.no_conversations': 'No conversations yet',
    'inbox.no_conversations_desc': 'Conversations will appear here when customers start chatting',
    'inbox.select_conversation': 'Select a conversation to start',
    'inbox.active_now': 'Active now',
    'inbox.transfer_agent': 'Transfer to agent',
    'inbox.mark': 'Mark',
    'inbox.resolve': 'Resolve',
    'inbox.type_message': 'Type a message...',
    'inbox.low_confidence': 'Low AI confidence - may need intervention',
    'inbox.user_info': 'User Information',
    'inbox.name': 'Name',
    'inbox.channel': 'Channel',
    'inbox.status': 'Status',
    'inbox.tags': 'Tags',
    'inbox.new_customer': 'New Customer',
    'inbox.inquiry': 'Inquiry',
    'inbox.new_conversation': 'New Conversation',
    'inbox.delete_conversation': 'Delete Conversation',
    'inbox.edit_tags': 'Edit Tags',
    'inbox.assign_agent': 'Assign Agent',

    // Channels
    'channels.title': 'Channels & Connections',
    'channels.subtitle': 'View the active channel for your bot',
    'channels.current_bot': 'Current Bot',
    'channels.bot_name': 'Bot Name',
    'channels.status': 'Status',
    'channels.connected': 'Active',
    'channels.pending': 'Not Active',
    'channels.disconnected': 'Not Active',
    'channels.note': 'Channel Management',
    'channels.note_text': 'Your bot connects to one primary channel. You can manage connection details in Settings.',

    // Settings
    'settings.title': 'Settings',
    'settings.manage': 'Manage your bot settings',
    'settings.bot_instructions': 'Bot Instructions',
    'settings.no_instructions': 'No instructions set yet',
    'settings.bot_status': 'Bot Status',
    'settings.active': 'Active',
    'settings.inactive': 'Inactive',
    'settings.created_date': 'Created Date',
    'settings.no_bot': 'No Bot Selected',
    'settings.no_bot_desc': 'Select a bot from the sidebar to view its settings',

    // Dashboard
    'dashboard.distribution': 'Distribution',
    'dashboard.complete': 'Complete',
    'dashboard.incomplete': 'Incomplete',
    'dashboard.pending': 'Pending',
    'dashboard.activity': 'Conversation Activity',
    'dashboard.charts_soon': 'Charts and detailed analytics will appear here soon',
    'dashboard.response_time': 'Response Time',
    'dashboard.performance': 'Performance',

    // Common Actions
    'action.create': 'Create',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.confirm': 'Confirm',
    'action.close': 'Close',
  },
  ar: {
    // Brand
    'brand.name': 'فهيم',
    'brand.tagline': 'دعم عملاء ذكي معمول للماركت العربي',

    // Navigation
    'nav.home': 'الرئيسية',
    'nav.pricing': 'الخطط والأسعار',
    'nav.login': 'تسجيل دخول',
    'nav.register': 'إنشاء حساب',
    'nav.search': 'ابحث...',
    'nav.create': 'إنشاء جديد',
    'nav.notifications': 'الإشعارات',
    'nav.no_notifications': 'لا توجد إشعارات جديدة',
    'nav.email': 'البريد الإلكتروني',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل خروج',
    'nav.profile': 'الملف الشخصي',

    // Footer
    'footer.quick_links': 'روابط سريعة',
    'footer.legal': 'قانوني',
    'footer.contact': 'تواصل معنا',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الاستخدام',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.twitter': 'تويتر',
    'footer.facebook': 'فيسبوك',
    'footer.linkedin': 'لينكدإن',

    // Login Page
    'login.welcome_back': 'مرحباً بعودتك',
    'login.subtitle': 'سجل دخولك للوصول إلى لوحة التحكم',
    'login.email': 'البريد الإلكتروني',
    'login.email_placeholder': 'example@example.com',
    'login.password': 'كلمة المرور',
    'login.password_placeholder': '••••••••',
    'login.submit': 'تسجيل الدخول',
    'login.loading': 'جارٍ تسجيل الدخول...',
    'login.no_account': 'ليس لديك حساب؟',
    'login.create_account': 'أنشئ حساباً الآن',
    'login.new_here': 'جديد هنا؟',
    'login.error': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',

    // Onboarding Page
    'onboarding.welcome': 'مرحباً',
    'onboarding.subtitle': 'دعنا نعدّ حسابك لتحقيق أقصى استفادة',
    'onboarding.step.company': 'الشركة',
    'onboarding.step.usecase': 'الاستخدام',
    'onboarding.step.languages': 'اللغات',
    'onboarding.company.title': 'ما اسم شركتك أو مشروعك؟',
    'onboarding.company.subtitle': 'سنستخدم هذا الاسم في بيانات حسابك',
    'onboarding.company.placeholder': 'مثال: شركة النجم',
    'onboarding.usecase.title': 'كيف ستستخدم فهيم؟',
    'onboarding.usecase.subtitle': 'اختر الحالة الأساسية لاستخدامك',
    'onboarding.usecase.support': 'دعم العملاء',
    'onboarding.usecase.sales': 'المبيعات',
    'onboarding.usecase.education': 'التعليم',
    'onboarding.usecase.healthcare': 'الصحة',
    'onboarding.usecase.ecommerce': 'التجارة الإلكترونية',
    'onboarding.usecase.other': 'أخرى',
    'onboarding.languages.title': 'ما لغات البوت؟',
    'onboarding.languages.subtitle': 'اختر اللغات التي سيتحدث بها بوتك',
    'onboarding.prev': 'السابق',
    'onboarding.next': 'التالي',
    'onboarding.finish': 'إنهاء',
    'onboarding.finishing': 'جارٍ الإنهاء...',

    // Register Page
    'register.title': 'ابدأ مع فهيم',
    'register.subtitle': 'أنشئ حسابك المجاني الآن',
    'register.first_name': 'الاسم الأول',
    'register.last_name': 'الاسم الأخير',
    'register.email': 'البريد الإلكتروني',
    'register.phone': 'رقم الهاتف',
    'register.password': 'كلمة المرور',
    'register.confirm_password': 'تأكيد كلمة المرور',
    'register.password_hint': 'يجب أن تكون كلمة المرور 8 أحرف على الأقل',
    'register.submit': 'إنشاء حساب',
    'register.loading': 'جارٍ إنشاء الحساب...',
    'register.has_account': 'لديك حساب بالفعل؟',
    'register.sign_in': 'سجل دخول',
    'register.error.first_name': 'الاسم الأول مطلوب',
    'register.error.last_name': 'الاسم الأخير مطلوب',
    'register.error.email': 'البريد الإلكتروني مطلوب',
    'register.error.phone': 'رقم الهاتف مطلوب',
    'register.error.password_length': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    'register.error.password_match': 'كلمات المرور غير متطابقة',
    'register.error.general': 'حدث خطأ أثناء إنشاء الحساب',
    'dashboard.title': 'لوحة التحكم',
    'dashboard.subtitle': 'ملخص أداء بوتاتك',
    'dashboard.daily_chats': 'المحادثات اليومية',
    'dashboard.customer_satisfaction': 'رضا العملاء',
    'dashboard.active_users': 'المستخدمين النشطين',
    'dashboard.growth': 'النمو',
    'dashboard.coming_soon': 'المزيد قريباً',
    'dashboard.advanced_analytics': 'سيتم إضافة تحليلات متقدمة وتقارير مفصلة قريباً',
    'knowledge.title': 'المعرفة والتعليمات',
    'knowledge.subtitle': 'أضف المعرفة والتعليمات لبوتك',
    'knowledge.add_new': 'إضافة معرفة جديدة',
    'knowledge.manual_text': 'نص يدوي',
    'knowledge.upload_file': 'رفع ملف',
    'knowledge.title_label': 'العنوان',
    'knowledge.title_placeholder': 'مثال: سياسة الاسترجاع',
    'knowledge.description_label': 'الوصف',
    'knowledge.description_placeholder': 'أدخل المعرفة التي تريد إضافتها...',
    'knowledge.add': 'إضافة',
    'knowledge.cancel': 'إلغاء',
    'knowledge.drag_files': 'اسحب الملفات هنا أو انقر للرفع',
    'knowledge.file_types': 'PDF, DOCX, TXT, CSV (حد أقصى 10 MB لكل ملف)',
    'knowledge.upload': 'رفع الملف',
    'knowledge.no_knowledge': 'لا توجد معرفة مضافة',
    'knowledge.no_knowledge_desc': 'ابدأ بإضافة المعرفة والتعليمات لبوتك',
    'knowledge.add_now': 'أضف الآن',
    'knowledge.type.manual': 'نص يدوي',
    'knowledge.type.product': 'منتج',
    'knowledge.type.file': 'ملف',
    'knowledge.content_label': 'المحتوى',
    'knowledge.content_placeholder': 'اكتب المحتوى هنا...',
    'knowledge.product_name': 'اسم المنتج',
    'knowledge.price': 'السعر',
    'knowledge.category': 'الفئة',
    'knowledge.description': 'الوصف',
    'knowledge.drag_drop': 'اسحب الملف هنا أو اضغط للاختيار',
    'knowledge.supported_formats': 'الصيغ المدعومة: PDF, DOC, DOCX',
    'knowledge.error.unsupported': 'صيغة ملف غير مدعومة. (PDF, DOC, DOCX فقط)',
    'knowledge.error.too_large': 'حجم الملف كبير جداً (الأقصى 10 ميجا)',
    'profile.title': 'الملف الشخصي',
    'profile.edit': 'تعديل الملف الشخصي',
    'profile.personal_info': 'المعلومات الشخصية',
    'profile.personal_info_desc': 'إدارة بياناتك الشخصية الأساسية',
    'profile.first_name': 'الاسم الأول',
    'profile.last_name': 'الاسم الأخير',
    'profile.phone': 'رقم الهاتف',
    'profile.not_provided': 'غير متوفر',
    'profile.security': 'الأمان والحساب',
    'profile.security_desc': 'إعدادات الأمان والخصوصية',
    'profile.status': 'حالة الحساب',
    'profile.active': 'نشط',
    'profile.verified': 'موثق',
    'profile.join_date': 'تاريخ الانضمام',
    'profile.bot_settings': 'إعدادات البوت',
    'profile.bot_settings_desc': 'هل تريد تغيير إعدادات البوت الخاص بك؟',
    'profile.go_to_settings': 'اذهب للإعدادات',
    'profile.save_changes': 'حفظ التغييرات',
    'sidebar.messages': 'الرسائل',
    'sidebar.knowledge': 'قاعدة المعرفة',
    'sidebar.channels': 'القنوات',
    'sidebar.inbox': 'الصندوق الوارد',
    'sidebar.settings': 'الإعدادات',
    'sidebar.active_bot': 'البوت النشط',
    'sidebar.new_bot': 'بوت جديد',
    'sidebar.language': 'اللغة',
    'sidebar.no_bot': 'لم يتم اختيار بوت',
    'sidebar.menu': 'القائمة',
    'sidebar.profile': 'الملف الشخصي',
    'sidebar.logout': 'تسجيل خروج',
    'auth.welcome_back': 'مرحباً بك مجدداً!',
    'auth.account_created': 'تم إنشاء الحساب بنجاح!',
    'auth.logged_out': 'تم تسجيل الخروج بنجاح',
    'auth.login_failed': 'فشل تسجيل الدخول',
    'auth.register_failed': 'فشل إنشاء الحساب',
    'auth.onboarding_complete': 'تم إكمال الإعداد بنجاح!',
    'auth.onboarding_failed': 'فشل حفظ بيانات الإعداد',
    'auth.onboarding_saving': 'جاري حفظ بيانات النشاط...',
    'auth.already_logged_in': 'أنت مسجل دخولك بالفعل!',
    'error.invalid_credentials': 'بيانات اعتماد غير صحيحة',
    'error.user_not_found': 'المستخدم غير موجود',
    'error.incorrect_password': 'كلمة المرور غير صحيحة',
    'error.unsupported_file': 'نوع الملف غير مدعوم. استخدم: PDF, DOCX, TXT, CSV',
    'error.file_too_large': 'حجم الملف يجب أن يكون أقل من 10 MB',
    'hero.title_start': 'جهز وكيلك الذكي في',
    'hero.title_end': 'دقايق',
    'hero.description': 'دعم عملاء بيحس زي البشر، حتى لو كان AI. فهيم بيكتشف المشاعر، بيتعامل مع الاستفسارات الروتينية، وبيحول الحالات المعقدة بسلاسة.',
    'hero.cta': 'ابدأ التجربة المجانية',
    'hero.assistant_icon': 'فـ',
    'hero.assistant_name': 'فهيم',
    'hero.online': 'متصل الآن',
    'hero.greeting': 'مرحباً! كيف أقدر أساعدك النهارده؟ 👋',
    'hero.user_message': 'عايز أعرف مواعيد العمل',
    'hero.bot_response': 'أكيد! إحنا شغالين من الساعة 9 صباحاً لحد 6 مساءً، من السبت للخميس 🕐',
    'hero.input_placeholder': 'اكتب رسالتك...',
    'features.title': 'لماذا تختار فهيم؟',
    'features.analytics': 'تحليلات شاملة',
    'features.analytics_desc': 'تتبع أداء بوتاتك وفهم سلوك العملاء',
    'features.security': 'أمان عالي',
    'features.security_desc': 'حماية بيانات عملائك بأعلى معايير الأمان',
    'features.customization': 'سهولة التخصيص',
    'features.customization_desc': 'خصص البوت حسب احتياجات عملك',
    'features.support': 'دعم فني متميز',
    'features.support_desc': 'فريق دعم متاح 24/7 لمساعدتك',
    'features.leads': 'عملاء محتملين',
    'features.leads_desc': 'فهيم بيستخرج العملاء المحتملين من المحادثات',
    'features.integration': 'اتصال',
    'features.integration_desc': 'فهيم بيرد على كل عميل، على كل منصة',
    'pricing.title': 'أسعار بسيطة وشفافة',
    'pricing.subtitle': 'اختر الخطة المناسبة لاحتياجات عملك',
    'pricing.trial': 'الباقة التجريبية',
    'pricing.trial_desc': 'للعاملين بدوام جزئي',
    'pricing.trial_cta': 'ابدأ الآن',
    'pricing.starter': 'باقة البداية',
    'pricing.starter_desc': 'للعاملين بدوام كامل',
    'pricing.pro': 'الباقة المتطورة',
    'pricing.pro_desc': 'للمؤسسات الكبرى',
    'pricing.free': 'مجاني',
    'pricing.per_month': '/شهر',
    'pricing.messages_100': '100 رسالة شهرياً',
    'pricing.messages_1k': '1,000 رسالة شهرياً',
    'pricing.messages_5k': '5,000 رسالة شهرياً',
    'pricing.agents_1': 'وكيل واحد',
    'pricing.agents_3': '3 وكلاء',
    'pricing.agents_10': '10 وكلاء',
    'pricing.platform_1': 'منصة واحدة',
    'pricing.platform_3': '3 منصات',
    'pricing.platform_unlimited': 'منصات غير محدودة',
    'pricing.basic_support': 'دعم فني أساسي',
    'pricing.priority_support': 'دعم فني ذو أولوية',
    'pricing.custom_support': 'دعم فني مخصص 24/7',
    'pricing.advanced_analytics': 'تحليلات متقدمة',
    'pricing.custom_analytics': 'تحليلات مخصصة',
    'pricing.custom_integrations': 'تكاملات مخصصة',
    'trusted.title': 'موثوق من قبل قادة الصناعة',
    'trusted.subtitle': 'آلاف الشركات تستخدم فهيم لتحسين دعم عملائهم',
    'trusted.companies': 'الشركات التي تستخدم فهيم',
    'trusted.conversations': 'المحادثات المعالجة',
    'trusted.uptime': 'ضمان التوفر',
    'cta.title': 'جاهز تحسّن خدمة عملائك؟',
    'cta.description': 'انضم لآلاف الشركات التي تستخدم فهيم لتقديم دعم عملاء استثنائي. ابدأ تجربتك المجانية اليوم بدون الحاجة لبطاقة ائتمان.',
    'cta.button_primary': 'ابدأ التجربة المجانية',
    'cta.button_secondary': 'عرض الأسعار',
    'cta.no_credit_card': 'بدون بطاقة ائتمان. سجل فقط',

    // Inbox
    'inbox.title': 'الصندوق الوارد',
    'inbox.conversations': 'المحادثات',
    'inbox.search': 'البحث في المحادثات...',
    'inbox.filter_all': 'الكل',
    'inbox.filter_active': 'نشط',
    'inbox.filter_pending': 'قيد الانتظار',
    'inbox.filter_resolved': 'تم الحل',
    'inbox.no_conversations': 'لا توجد محادثات بعد',
    'inbox.no_conversations_desc': 'ستظهر المحادثات هنا عندما يبدأ العملاء في الدردشة',
    'inbox.select_conversation': 'اختر محادثة للبدء',
    'inbox.active_now': 'نشط الآن',
    'inbox.transfer_agent': 'تحويل للوكيل',
    'inbox.mark': 'وضع علامة',
    'inbox.resolve': 'حل المحادثة',
    'inbox.type_message': 'اكتب رسالتك...',
    'inbox.low_confidence': 'ثقة AI منخفضة - قد تحتاج للتدخل',
    'inbox.user_info': 'معلومات المستخدم',
    'inbox.name': 'الاسم',
    'inbox.channel': 'القناة',
    'inbox.status': 'الحالة',
    'inbox.tags': 'الوسوم',
    'inbox.new_customer': 'عميل جديد',
    'inbox.inquiry': 'استفسار',
    'inbox.new_conversation': 'محادثة جديدة',
    'inbox.delete_conversation': 'حذف المحادثة',
    'inbox.edit_tags': 'تعديل الوسوم',
    'inbox.assign_agent': 'تعيين وكيل',

    // Channels
    'channels.title': 'الاتصالات والقنوات',
    'channels.subtitle': 'عرض القناة النشطة للبوت الخاص بك',
    'channels.current_bot': 'البوت الحالي',
    'channels.bot_name': 'اسم البوت',
    'channels.status': 'الحالة',
    'channels.connected': 'نشط',
    'channels.pending': 'غير نشط',
    'channels.disconnected': 'غير نشط',
    'channels.note': 'إدارة القناة',
    'channels.note_text': 'يتصل البوت بقناة رئيسية واحدة. يمكنك إدارة تفاصيل الاتصال من الإعدادات.',

    // Settings
    'settings.title': 'الإعدادات',
    'settings.manage': 'إدارة إعدادات البوت',
    'settings.bot_instructions': 'تعليمات البوت',
    'settings.no_instructions': 'لم يتم تعيين تعليمات بعد',
    'settings.bot_status': 'حالة البوت',
    'settings.active': 'نشط',
    'settings.inactive': 'غير نشط',
    'settings.created_date': 'تاريخ الإنشاء',
    'settings.no_bot': 'لم يتم اختيار بوت',
    'settings.no_bot_desc': 'اختر بوتاً من الشريط الجانبي لعرض إعداداته',

    // Dashboard
    'dashboard.distribution': 'التوزيع',
    'dashboard.complete': 'مكتمل',
    'dashboard.incomplete': 'غير مكتمل',
    'dashboard.pending': 'قيد الانتظار',
    'dashboard.activity': 'نشاط المحادثات',
    'dashboard.charts_soon': 'سيتم عرض الرسوم البيانية التفصيلية قريباً',
    'dashboard.response_time': 'وقت الاستجابة',
    'dashboard.performance': 'الأداء',

    // Common Actions
    'nav.dashboard': 'لوحة التحكم',
    'action.create': 'إنشاء',
    'action.edit': 'تعديل',
    'action.delete': 'حذف',
    'action.save': 'حفظ',
    'action.cancel': 'إلغاء',
    'action.confirm': 'تأكيد',
    'action.close': 'إغلاق',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ar')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const stored = localStorage.getItem('faheem_language') as Language | null
    const langToUse = (stored && (stored === 'en' || stored === 'ar')) ? stored : 'ar'
    setLanguageState(langToUse)

    // Update document attributes
    if (typeof document !== 'undefined') {
      document.documentElement.dir = langToUse === 'ar' ? 'rtl' : 'ltr'
      document.documentElement.lang = langToUse
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('faheem_language', lang)

    // Update document attributes immediately
    if (typeof document !== 'undefined') {
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
      document.documentElement.lang = lang
    }
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
